#!/bin/sh
#confirm=NO
#Get Number of opened windows in all workspaces
OPENWIN=$(wmctrl -l|awk '{$3=""; $2=""; $1=""; print $0}' | wc -l)

#Get screen resolution and calculate the center of the screen
RES=$(xrandr | grep '*' | awk '{print $1}')

IFS='x' read -a R <<< "$RES"

HALFWIDTH=$(echo "${R[0]}/2" | bc )
HALFHEIGHT=$(echo "${R[1]}/2" | bc )
#move the mouse in the middle so the dialog spawns in the middle too
xdotool mousemove $HALFWIDTH $HALFHEIGHT;

#DIALOG
if [[ $OPENWIN -gt 0 ]]; then
        zenity --width=200 --height=100 --default-cancel --question  --text="<span size=\"xx-large\">Shutdown.</span>\n\nWant to <b>fuck off</b>?\nYou have $OPENWIN windows opened" --title="Shutdown" && confirm=YES || confirm=NO
    else
        zenity --width=200 --height=100 --default-cancel --question  --text="<span size=\"xx-large\">Shutdown.</span>\n\nWant to <b>fuck off</b>?" --title="Shutdown" && confirm=YES || confirm=NO
fi


if [[ $confirm == "YES" ]] ; then
    shutdown now
    else
        exit
fi
