#!/bin/zsh
if [[ $1 == "z" ]]; then
    urxvtc -name zemnl -e zsh -c "tmux attach-session -d" &
	elif [[ $1 == "n" ]]; then
	urxvtc -e zsh -c "tmux attach-session -d" &
	elif [[ $1 == "l" ]]; then
	urxvtc  -name z -fn xft:Hack-10 -fb xft:Hack:bold:10 -geometry 198x55 -e zsh -c "tmux attach-session -d" &
	elif [[ $1 == "tr" ]]; then
	urxvtc -depth 32 -bg rgba:1a00/1b00/2200/ddcc -name z -e zsh -c "tmux attach-session -d" &
    else
    urxvtc -name z  -e zsh -c "tmux attach-session -d" &

fi
